### ISSUE TITLE
Question related to removed overloaded 'map' methods in  AbstractMapping

### ISSUE THREAD

**Issue by kowalczm** [PgBulkInsert/PgBulkInsert#93]
Hi,
In https://github.com/PgBulkInsert/PgBulkInsert/commit/f051e55ae6ae43fc54ec32a7fe393d5f34047d11
I saw that few oveloaded functions were removed in AbstractMapping (mapBoolean, mapLong). Is it intentional?

**Comment by bytefish** [comment]
Semi-Intentional. I thought they are not used anymore and I was throwing some code out. I was a little over the top. 😓

I'll re-add them and release an update to Maven. Give me a moment.

**Comment by kowalczm** [comment]
Ok, I'm not not involved to projects related with this library but having classes with with primitve types is quite common and converting them to object types (boxing) is very expensive especially in cases when you process millions of millions of  such objects

**Comment by bytefish** [comment]
Now looking at the code, I remember why I did this... If you overload the methods in such a way, Java with its glorious Type Erasure cannot make sense, which method applies:

![image](https://user-images.githubusercontent.com/239373/84360694-caa86b00-abca-11ea-9e81-c66c60640bf2.png)

This is a problem, because I want people to be able to write stuff like the above.

I will change the API Surface to ``mapBoolean`` / ``mapBooleanPrimitive``, so you can explictly choose which way to go and not have to overload the Functional Interfaces.

I will also add a part to the README.

**Comment by bytefish** [comment]
I've added the functions again, but one has to decide explicitly wether to use the Primitive type or not. This is not perfect, but at least it doesn't lead to the kind of error above.
